package addEmp.model.bc.views.common;

import oracle.jbo.Row;
import oracle.jbo.domain.BlobDomain;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 10 00:15:30 AST 2019
// ---------------------------------------------------------------------
public interface EmpAttachmentsVORow extends Row {
    BlobDomain getAttachedFile();

    oracle.jbo.domain.Number getAttachmentType();

    oracle.jbo.domain.Number getEmpAttachmentId();

    void setAttachedFile(BlobDomain value);

    void setAttachmentType(oracle.jbo.domain.Number value);

    void setEmpAttachmentId(oracle.jbo.domain.Number value);
}

