package addEmp.model.bc.views;

import addEmp.model.bc.views.common.EmpAttachmentsVO;

import model.shared.extensions.ExtViewObjectImpl;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 10 00:05:27 AST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpAttachmentsVOImpl extends ExtViewObjectImpl implements EmpAttachmentsVO {
    /**
     * This is the default constructor (do not remove).
     */
    public EmpAttachmentsVOImpl() {
    }

    /**
     * Returns the bind variable value for bindEmpAttachID.
     * @return bind variable value for bindEmpAttachID
     */
    public Number getbindEmpAttachID() {
        return (Number) getNamedWhereClauseParam("bindEmpAttachID");
    }

    /**
     * Sets <code>value</code> for bind variable bindEmpAttachID.
     * @param value value to bind as bindEmpAttachID
     */
    public void setbindEmpAttachID(Number value) {
        setNamedWhereClauseParam("bindEmpAttachID", value);
    }

    public Row getAttachmentById(Number aId) {
        setbindEmpAttachID(aId);
        executeQuery();
        Row row = first();
        return row;
    }
}

