package addEmp.model.bc.views;

import model.shared.extensions.ExtViewObjectImpl;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 30 22:40:53 AST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SkillsVOImpl extends ExtViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SkillsVOImpl() {
    }

    /**Method to revert changes of current row
     * @param curRow
     */
    public void revertChangesCurrentRow(Row curRow) {
        if (curRow != null) {
            curRow.refresh(Row.REFRESH_REMOVE_NEW_ROWS | Row.REFRESH_FORGET_NEW_ROWS | Row.REFRESH_UNDO_CHANGES |
                           Row.REFRESH_WITH_DB_FORGET_CHANGES);
        }
    }
}

