package addEmp.model.bc.am;

import addEmp.model.bc.views.EmpAttachmentsVOImpl;

import model.shared.extensions.ExtApplicationModuleImpl;

import model.shared.extensions.ExtViewObjectImpl;

import oracle.jbo.server.ViewLinkImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 09 23:32:56 AST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HrAddEmpAppModuleImpl extends ExtApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HrAddEmpAppModuleImpl() {
    }

    /**
     * Container's getter for BaseEmployees1.
     * @return BaseEmployees1
     */
    public ExtViewObjectImpl getBaseEmployees1() {
        return (ExtViewObjectImpl) findViewObject("BaseEmployees1");
    }

    /**
     * Container's getter for Contract1.
     * @return Contract1
     */
    public ExtViewObjectImpl getContract1() {
        return (ExtViewObjectImpl) findViewObject("Contract1");
    }

    /**
     * Container's getter for DrivingLicense1.
     * @return DrivingLicense1
     */
    public ExtViewObjectImpl getDrivingLicense1() {
        return (ExtViewObjectImpl) findViewObject("DrivingLicense1");
    }

    /**
     * Container's getter for EmergencyContactPerson1.
     * @return EmergencyContactPerson1
     */
    public ExtViewObjectImpl getEmergencyContactPerson1() {
        return (ExtViewObjectImpl) findViewObject("EmergencyContactPerson1");
    }

    /**
     * Container's getter for EmpContactHomeCountry1.
     * @return EmpContactHomeCountry1
     */
    public ExtViewObjectImpl getEmpContactHomeCountry1() {
        return (ExtViewObjectImpl) findViewObject("EmpContactHomeCountry1");
    }

    /**
     * Container's getter for EmpEducation1.
     * @return EmpEducation1
     */
    public ExtViewObjectImpl getEmpEducation1() {
        return (ExtViewObjectImpl) findViewObject("EmpEducation1");
    }

    /**
     * Container's getter for EmployeeAddress1.
     * @return EmployeeAddress1
     */
    public ExtViewObjectImpl getEmployeeAddress1() {
        return (ExtViewObjectImpl) findViewObject("EmployeeAddress1");
    }

    /**
     * Container's getter for EmployeeCourses1.
     * @return EmployeeCourses1
     */
    public ExtViewObjectImpl getEmployeeCourses1() {
        return (ExtViewObjectImpl) findViewObject("EmployeeCourses1");
    }

    /**
     * Container's getter for EmployeeExperience1.
     * @return EmployeeExperience1
     */
    public ExtViewObjectImpl getEmployeeExperience1() {
        return (ExtViewObjectImpl) findViewObject("EmployeeExperience1");
    }

    /**
     * Container's getter for EmployeeTermination1.
     * @return EmployeeTermination1
     */
    public ExtViewObjectImpl getEmployeeTermination1() {
        return (ExtViewObjectImpl) findViewObject("EmployeeTermination1");
    }

    /**
     * Container's getter for EmpSkills1.
     * @return EmpSkills1
     */
    public ExtViewObjectImpl getEmpSkills1() {
        return (ExtViewObjectImpl) findViewObject("EmpSkills1");
    }

    /**
     * Container's getter for PassportInfo1.
     * @return PassportInfo1
     */
    public ExtViewObjectImpl getPassportInfo1() {
        return (ExtViewObjectImpl) findViewObject("PassportInfo1");
    }

    /**
     * Container's getter for Depeendents1.
     * @return Depeendents1
     */
    public ExtViewObjectImpl getDepeendents1() {
        return (ExtViewObjectImpl) findViewObject("Depeendents1");
    }

    /**
     * Container's getter for IdInfo1.
     * @return IdInfo1
     */
    public ExtViewObjectImpl getIdInfo1() {
        return (ExtViewObjectImpl) findViewObject("IdInfo1");
    }

    /**
     * Container's getter for EmpAttachments1.
     * @return EmpAttachments1
     */
    public EmpAttachmentsVOImpl getEmpAttachments1() {
        return (EmpAttachmentsVOImpl) findViewObject("EmpAttachments1");
    }

    /**
     * Container's getter for EmployeeContractVL1.
     * @return EmployeeContractVL1
     */
    public ViewLinkImpl getEmployeeContractVL1() {
        return (ViewLinkImpl) findViewLink("EmployeeContractVL1");
    }

    /**
     * Container's getter for EmpDrivingLicenseVL1.
     * @return EmpDrivingLicenseVL1
     */
    public ViewLinkImpl getEmpDrivingLicenseVL1() {
        return (ViewLinkImpl) findViewLink("EmpDrivingLicenseVL1");
    }

    /**
     * Container's getter for EmployeeEmergencyContactPersonsVL1.
     * @return EmployeeEmergencyContactPersonsVL1
     */
    public ViewLinkImpl getEmployeeEmergencyContactPersonsVL1() {
        return (ViewLinkImpl) findViewLink("EmployeeEmergencyContactPersonsVL1");
    }

    /**
     * Container's getter for EmployeeEmpContactHomeCountryVL1.
     * @return EmployeeEmpContactHomeCountryVL1
     */
    public ViewLinkImpl getEmployeeEmpContactHomeCountryVL1() {
        return (ViewLinkImpl) findViewLink("EmployeeEmpContactHomeCountryVL1");
    }

    /**
     * Container's getter for EmployeeEmpEducationVL1.
     * @return EmployeeEmpEducationVL1
     */
    public ViewLinkImpl getEmployeeEmpEducationVL1() {
        return (ViewLinkImpl) findViewLink("EmployeeEmpEducationVL1");
    }

    /**
     * Container's getter for EmpEmployeeAddressVL1.
     * @return EmpEmployeeAddressVL1
     */
    public ViewLinkImpl getEmpEmployeeAddressVL1() {
        return (ViewLinkImpl) findViewLink("EmpEmployeeAddressVL1");
    }

    /**
     * Container's getter for EmployeeEmpCoursesVL1.
     * @return EmployeeEmpCoursesVL1
     */
    public ViewLinkImpl getEmployeeEmpCoursesVL1() {
        return (ViewLinkImpl) findViewLink("EmployeeEmpCoursesVL1");
    }

    /**
     * Container's getter for EmpEmployeeCoursesVL1.
     * @return EmpEmployeeCoursesVL1
     */
    public ViewLinkImpl getEmpEmployeeCoursesVL1() {
        return (ViewLinkImpl) findViewLink("EmpEmployeeCoursesVL1");
    }

    /**
     * Container's getter for EmpEmployeeTerminationVL1.
     * @return EmpEmployeeTerminationVL1
     */
    public ViewLinkImpl getEmpEmployeeTerminationVL1() {
        return (ViewLinkImpl) findViewLink("EmpEmployeeTerminationVL1");
    }

    /**
     * Container's getter for EmpEmpSkillsVL1.
     * @return EmpEmpSkillsVL1
     */
    public ViewLinkImpl getEmpEmpSkillsVL1() {
        return (ViewLinkImpl) findViewLink("EmpEmpSkillsVL1");
    }

    /**
     * Container's getter for EmpPassportVL1.
     * @return EmpPassportVL1
     */
    public ViewLinkImpl getEmpPassportVL1() {
        return (ViewLinkImpl) findViewLink("EmpPassportVL1");
    }

    /**
     * Container's getter for EmployeeDependentVL1.
     * @return EmployeeDependentVL1
     */
    public ViewLinkImpl getEmployeeDependentVL1() {
        return (ViewLinkImpl) findViewLink("EmployeeDependentVL1");
    }

    /**
     * Container's getter for EmpIdInfoVL1.
     * @return EmpIdInfoVL1
     */
    public ViewLinkImpl getEmpIdInfoVL1() {
        return (ViewLinkImpl) findViewLink("EmpIdInfoVL1");
    }

    /**
     * Container's getter for EmpEmpAttachmentVL1.
     * @return EmpEmpAttachmentVL1
     */
    public ViewLinkImpl getEmpEmpAttachmentVL1() {
        return (ViewLinkImpl) findViewLink("EmpEmpAttachmentVL1");
    }

    /**
     * Container's getter for EmpAttachmentsData1.
     * @return EmpAttachmentsData1
     */
    public ExtViewObjectImpl getEmpAttachmentsData1() {
        return (ExtViewObjectImpl) findViewObject("EmpAttachmentsData1");
    }

    /**
     * Container's getter for EmpEmpAttVL1.
     * @return EmpEmpAttVL1
     */
    public ViewLinkImpl getEmpEmpAttVL1() {
        return (ViewLinkImpl) findViewLink("EmpEmpAttVL1");
    }
}

